; Script generated by the Inno Setup Script Wizard.
; And some of the other stuff made by me!
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "CatSlicer"
#define MyAppVersion "1.0"
#define MyAppPublisher "jhfhngj"
#define MyAppURL "https://github.com/jhfhngj/CatSlicer-ME"
#define MyAppExeName "fix.exe"
#expr EmitLanguagesSection

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D2BA2812-ECD2-4EF9-86A9-D24FFC7BA3E3}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=C:\Users\your username\CatSlicer\CatSlicer-ME\LICENSE
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=mysetup
SolidCompression=yes
WizardStyle=classic dynamic windows11

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\frontend.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\forrender.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\render.mp4"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\render.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\slice.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\install.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\flashme.ino"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\your username\CatSlicer\CatSlicer-ME\requirements.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\install.exe"; Description: "Install required libraries and applications"; Flags: nowait postinstall skipifsilent
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

